version: '3'

services:
  web:
    image: nginx
    networks: 
      - web
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "traefik.frontend.rule=Host:www.luckfindersalmanac.com,luckfindersalmanac.com"
      - "traefik.frontend.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSIncludeSubdomains=false"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.docker.network=web"
      - "traefik.port=80"
      - "traefik.enabled=true"

networks:
  web:
    external: true