version: '3'

services:
  web:
    image: nginx
    networks: 
      - web
    volumes:
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=thegreatforest.nl
      - NGINX_PORT=80
    expose:
      - "8080"
    labels:
      - "traefik.frontend.rule=Host:www.thegreatforest.nl,thegreatforest.nl"
      - "traefik.frontend.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSIncludeSubdomains=false"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.docker.network=web"
      - "traefik.port=8080"
      - "traefik.enabled=true"